services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /opt/akademate/uptime-kuma/data:/app/data
    networks:
      - proxy
      - tenant-admin_internal

networks:
  proxy:
    external: true
  tenant-admin_internal:
    external: true
