export type ConnectorStatus = 'Available' | 'Connector-ready' | 'Roadmap' | 'Payment method'

export const integrationBrands = {
  stripe: { label: 'Stripe', asset: '/brands/stripe.svg', color: '#635BFF', status: 'Available' },
  paypal: {
    label: 'PayPal',
    asset: '/brands/paypal.svg',
    color: '#003087',
    status: 'Connector-ready',
  },
  sepa: {
    label: 'SEPA',
    asset: '/brands/sepa.svg',
    color: '#003399',
    status: 'Connector-ready',
    preserveColor: true,
  },
  visa: { label: 'Visa', asset: '/brands/visa.svg', color: '#1A1F71', status: 'Payment method' },
  mastercard: {
    label: 'Mastercard',
    asset: '/brands/mastercard.svg',
    color: '#EB001B',
    status: 'Payment method',
  },
  applepay: {
    label: 'Apple Pay',
    asset: '/brands/applepay.svg',
    color: '#111827',
    status: 'Payment method',
  },
  googlepay: {
    label: 'Google Pay',
    asset: '/brands/googlepay.svg',
    color: '#4285F4',
    status: 'Payment method',
  },
  adyen: { label: 'Adyen', asset: '/brands/adyen.svg', color: '#0ABF53', status: 'Roadmap' },
  klarna: { label: 'Klarna', asset: '/brands/klarna.svg', color: '#FFB3C7', status: 'Roadmap' },
  meta: { label: 'Meta', asset: '/brands/meta.svg', color: '#0866FF', status: 'Connector-ready' },
  googleads: {
    label: 'Google Ads',
    asset: '/brands/googleads.svg',
    color: '#4285F4',
    status: 'Connector-ready',
  },
  cloudflare: {
    label: 'Cloudflare',
    asset: '/brands/cloudflare.svg',
    color: '#F38020',
    status: 'Available',
  },
  googlecalendar: {
    label: 'Google Calendar',
    asset: '/brands/googlecalendar.svg',
    color: '#4285F4',
    status: 'Connector-ready',
  },
  zoom: { label: 'Zoom', asset: '/brands/zoom.svg', color: '#0B5CFF', status: 'Connector-ready' },
  googlemeet: {
    label: 'Google Meet',
    asset: '/brands/googlemeet.svg',
    color: '#00897B',
    status: 'Connector-ready',
  },
  youtube: {
    label: 'YouTube',
    asset: '/brands/youtube.svg',
    color: '#FF0000',
    status: 'Connector-ready',
  },
  vimeo: {
    label: 'Vimeo',
    asset: '/brands/vimeo.svg',
    color: '#1AB7EA',
    status: 'Connector-ready',
  },
  whatsapp: {
    label: 'WhatsApp',
    asset: '/brands/whatsapp.svg',
    color: '#25D366',
    status: 'Roadmap',
  },
  twilio: { label: 'Twilio', asset: '/brands/twilio.svg', color: '#F22F46', status: 'Roadmap' },
  xero: { label: 'Xero', asset: '/brands/xero.svg', color: '#13B5EA', status: 'Roadmap' },
  quickbooks: {
    label: 'QuickBooks',
    asset: '/brands/quickbooks.svg',
    color: '#2CA01C',
    status: 'Roadmap',
  },
  sage: { label: 'Sage', asset: '/brands/sage.svg', color: '#00D639', status: 'Roadmap' },
  odoo: { label: 'Odoo', asset: '/brands/odoo.svg', color: '#714B67', status: 'Roadmap' },
  sap: { label: 'SAP', asset: '/brands/sap.svg', color: '#0FAAFF', status: 'Roadmap' },
  zoho: { label: 'Zoho', asset: '/brands/zoho.svg', color: '#E42527', status: 'Roadmap' },
  erpnext: {
    label: 'ERPNext',
    asset: '/brands/erpnext.svg',
    color: '#0089FF',
    status: 'Roadmap',
  },
  invoiceninja: {
    label: 'Invoice Ninja',
    asset: '/brands/invoiceninja.svg',
    color: '#000000',
    status: 'Roadmap',
  },
  hubspot: {
    label: 'HubSpot',
    asset: '/brands/hubspot.svg',
    color: '#FF7A59',
    status: 'Roadmap',
  },
  mailchimp: {
    label: 'Mailchimp',
    asset: '/brands/mailchimp.svg',
    color: '#FFE01B',
    status: 'Roadmap',
  },
  tiktok: { label: 'TikTok', asset: '/brands/tiktok.svg', color: '#000000', status: 'Roadmap' },
  brevo: { label: 'Brevo', asset: '/brands/brevo.svg', color: '#0B996E', status: 'Roadmap' },
  pinterest: {
    label: 'Pinterest',
    asset: '/brands/pinterest.svg',
    color: '#BD081C',
    status: 'Roadmap',
  },
  resend: { label: 'Resend', asset: '/brands/resend.svg', color: '#000000', status: 'Roadmap' },
  gmail: { label: 'Gmail', asset: '/brands/gmail.svg', color: '#EA4335', status: 'Roadmap' },
  telegram: {
    label: 'Telegram',
    asset: '/brands/telegram.svg',
    color: '#26A5E4',
    status: 'Roadmap',
  },
  discord: {
    label: 'Discord',
    asset: '/brands/discord.svg',
    color: '#5865F2',
    status: 'Roadmap',
  },
  openai: { label: 'OpenAI', asset: '/brands/openai.svg', color: '#111827', status: 'Roadmap' },
  okta: { label: 'Okta', asset: '/brands/okta.svg', color: '#007DC1', status: 'Roadmap' },
  auth0: { label: 'Auth0', asset: '/brands/auth0.svg', color: '#EB5424', status: 'Roadmap' },
  zapier: {
    label: 'Zapier',
    asset: '/brands/zapier.svg',
    color: '#FF4F00',
    status: 'Connector-ready',
  },
  make: { label: 'Make', asset: '/brands/make.svg', color: '#6D00CC', status: 'Connector-ready' },
  n8n: { label: 'n8n', asset: '/brands/n8n.svg', color: '#EA4B71', status: 'Connector-ready' },
} as const

export type IntegrationBrandId = keyof typeof integrationBrands

export const homeIntegrationBrands: IntegrationBrandId[] = [
  'stripe',
  'paypal',
  'sepa',
  'meta',
  'googleads',
  'zoom',
  'cloudflare',
  'zapier',
]

export const integrationPillarBrands: Record<string, IntegrationBrandId[]> = {
  Payments: [
    'stripe',
    'paypal',
    'sepa',
    'visa',
    'mastercard',
    'applepay',
    'googlepay',
    'adyen',
    'klarna',
  ],
  Finance: ['xero', 'quickbooks', 'sage', 'odoo', 'sap', 'zoho', 'erpnext', 'invoiceninja'],
  Growth: ['meta', 'googleads', 'youtube', 'hubspot', 'mailchimp', 'tiktok', 'brevo', 'pinterest'],
  Communication: [
    'whatsapp',
    'twilio',
    'zoom',
    'googlemeet',
    'resend',
    'gmail',
    'telegram',
    'discord',
  ],
}
