export const academySetupStages = [
  {
    id: 'blueprint',
    step: '01',
    title: 'Academy blueprint',
    description: 'Define the academy model, teaching formats and launch plan.',
    visualLabel: 'Blueprint lines',
    image: '/images/academy-setup/academy-stage-01-blueprint.jpg',
    imageAlt: 'Isometric line blueprint of a compact two-storey academy',
    capabilities: ['Academy model', 'Teaching formats', 'Launch plan'],
  },
  {
    id: 'campuses',
    step: '02',
    title: 'Campuses and spaces',
    description: 'Shape campuses, rooms, facilities and online capacity.',
    visualLabel: 'Structure in place',
    image: '/images/academy-setup/academy-stage-02-structure.jpg',
    imageAlt: 'The same isometric academy with its foundation, frame and floor slabs built',
    capabilities: ['Multiple campuses', 'Rooms and facilities', 'Online campus'],
  },
  {
    id: 'programmes',
    step: '03',
    title: 'Programmes and offers',
    description: 'Configure offers, schedules, capacity and enrolment rules.',
    visualLabel: 'Building envelope',
    image: '/images/academy-setup/academy-stage-03-envelope.jpg',
    imageAlt: 'The same isometric academy with walls, roof and window frames installed',
    capabilities: ['Courses and cohorts', 'Schedules', 'Capacity and pricing'],
  },
  {
    id: 'people',
    step: '04',
    title: 'People and access',
    description: 'Prepare focused access for teams, teachers and learners.',
    visualLabel: 'Spaces prepared',
    image: '/images/academy-setup/academy-stage-04-spaces.jpg',
    imageAlt: 'The same isometric academy fitted with classrooms and a reception area',
    capabilities: ['Teams and roles', 'Teachers', 'Learners and families'],
  },
  {
    id: 'experience',
    step: '05',
    title: 'Learning and operations',
    description: 'Connect learning, payments, communication and reporting.',
    visualLabel: 'Identity applied',
    image: '/images/academy-setup/academy-stage-05-identity.jpg',
    imageAlt: 'The same completed academy with its identity and landscaping in place',
    capabilities: ['Campus and chat', 'Payments and finance', 'Integrations'],
  },
  {
    id: 'live',
    step: '06',
    title: 'Academy live',
    description: 'Complete readiness and launch under your academy identity.',
    visualLabel: 'Academy Live',
    image: '/images/academy-setup/academy-stage-06-live.jpg',
    imageAlt: 'The same completed academy live with warm classrooms and entrance lights',
    capabilities: ['Brand and website', 'Team ready', 'Launch complete'],
  },
] as const

export type AcademySetupStage = (typeof academySetupStages)[number]
export type AcademySetupStageId = AcademySetupStage['id']
