http:
  routers:
    uptime-kuma-akademate:
      rule: "Host(`status.akademate.com`)"
      entryPoints:
        - websecure
      service: uptime-kuma-svc
      middlewares:
        - kuma-headers
      tls:
        certresolver: letsencrypt

    uptime-kuma-cep:
      rule: "Host(`status.cepformacion.akademate.com`)"
      entryPoints:
        - websecure
      service: uptime-kuma-svc
      middlewares:
        - kuma-headers
      tls:
        certresolver: letsencrypt

  middlewares:
    kuma-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: ""
        contentSecurityPolicy: "frame-ancestors 'self' https://admin.akademate.com https://cepformacion.akademate.com"

  services:
    uptime-kuma-svc:
      loadBalancer:
        servers:
          - url: "http://uptime-kuma:3001"
