export const CEP_PARTNERS = [
  { name: 'Clínica Veterinaria Añaza', file: 'clinica-veterinaria-anaza.jpg' },
  { name: 'Clínica Veterinaria Duggi', file: 'clinica-veterinaria-duggi.jpg' },
  { name: 'Centro Veterinario Alper', file: 'centro-veterinario-alper.jpg' },
  { name: 'Aboras Obediencia', file: 'aboras-obediencia.jpg' },
  { name: 'CIDME', file: 'cidme.jpg' },
  { name: 'Mi Óptica Central', file: 'mi-optica-central.jpg' },
  { name: 'DKV', file: 'dkv.jpg' },
  { name: 'Farmacia Charco del Pino', file: 'farmacia-charco-del-pino.jpg' },
  { name: 'Farmacia Fañabé Playa', file: 'farmacia-fanabe-playa.jpg' },
  { name: 'Farmacia Golf del Sur', file: 'farmacia-golf-del-sur.jpg' },
  { name: 'Farmacia Igara', file: 'farmacia-igara.jpg' },
  { name: 'Farmacia La Comunitaria', file: 'farmacia-la-comunitaria.jpg' },
  { name: 'Farmacia La Fuente', file: 'farmacia-la-fuente.jpg' },
  { name: 'Farmacia Las Chafiras', file: 'farmacia-las-chafiras.jpg' },
  { name: 'Farmacia Los Abrigos', file: 'farmacia-los-abrigos.jpg' },
  { name: 'Farmacia Magma Adeje', file: 'farmacia-magma-adeje.jpg' },
  { name: 'Farmacia Plasencia El Médano', file: 'farmacia-plasencia-el-medano.jpg' },
  { name: 'Farmacia Valle San Lorenzo', file: 'farmacia-valle-san-lorenzo.jpg' },
  { name: 'Farmacia Santiago del Teide', file: 'farmacia-santiago-del-teide.jpg' },
  { name: 'Farmacia Las Torres', file: 'farmacia-las-torres.jpg' },
  { name: 'Farmacia Torviscas', file: 'farmacia-torviscas.jpg' },
  { name: 'Farmacia y Nutrición', file: 'farmacia-y-nutricion.jpg' },
  { name: 'Óptica Granadilla', file: 'optica-granadilla.jpg' },
  { name: 'Hospital Quirón Salud', file: 'hospital-quiron-salud.jpg' },
  { name: 'Óptica Grand Vision', file: 'optica-grand-vision.jpg' },
  { name: 'Clínica Veterinaria Okapi', file: 'clinica-veterinaria-okapi.jpg' },
  { name: 'Tienda de Animales Dingo', file: 'tienda-de-animales-dingo.jpg' },
  { name: 'Hospital Veterinario El Madroñal', file: 'hospital-veterinario-el-madronal.jpg' },
  { name: 'Hospital Veterinario Patas y Colas', file: 'hospital-veterinario-patas-y-colas.jpg' },
  { name: 'Clínica Veterinaria Hospivet Sur', file: 'clinica-veterinaria-hospivet-sur.jpg' },
  { name: 'Clínica Veterinaria Los Llanos', file: 'clinica-veterinaria-los-llanos.jpg' },
  { name: 'Alexandre Hotels', file: 'alexandre-hotels.jpg' },
  { name: 'Baobab Suites', file: 'baobab-suites.jpg' },
  { name: 'Be Live Hotels', file: 'be-live-hotels.jpg' },
  { name: 'H10 Hotels', file: 'h10-hotels.jpg' },
  { name: 'Iberostar Hotels', file: 'iberostar-hotels.jpg' },
] as const

export const PARTNER_ASSET_PREFIX = '/website/cep/partners/'
