/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Pacific/Midway' | 'Pacific/Niue' | 'Pacific/Honolulu' | 'Pacific/Rarotonga' | 'America/Anchorage' | 'Pacific/Gambier' | 'America/Los_Angeles' | 'America/Tijuana' | 'America/Denver' | 'America/Phoenix' | 'America/Chicago' | 'America/Guatemala' | 'America/New_York' | 'America/Bogota' | 'America/Caracas' | 'America/Santiago' | 'America/Buenos_Aires' | 'America/Sao_Paulo' | 'Atlantic/South_Georgia' | 'Atlantic/Azores' | 'Atlantic/Cape_Verde' | 'Europe/London' | 'Europe/Berlin' | 'Africa/Lagos' | 'Europe/Athens' | 'Africa/Cairo' | 'Europe/Moscow' | 'Asia/Riyadh' | 'Asia/Dubai' | 'Asia/Baku' | 'Asia/Karachi' | 'Asia/Tashkent' | 'Asia/Calcutta' | 'Asia/Dhaka' | 'Asia/Almaty' | 'Asia/Jakarta' | 'Asia/Bangkok' | 'Asia/Shanghai' | 'Asia/Singapore' | 'Asia/Tokyo' | 'Asia/Seoul' | 'Australia/Brisbane' | 'Australia/Sydney' | 'Pacific/Guam' | 'Pacific/Noumea' | 'Pacific/Auckland' | 'Pacific/Fiji';
export interface Config {
    auth: {
        users: UserAuthOperations;
    };
    blocks: {};
    collections: {
        tenants: Tenant;
        users: User;
        cycles: Cycle;
        campuses: Campus;
        'areas-formativas': AreasFormativa;
        'entidades-financiadoras': EntidadesFinanciadora;
        courses: Course;
        'course-runs': CourseRun;
        students: Student;
        enrollments: Enrollment;
        staff: Staff;
        campaigns: Campaign;
        ads_templates: AdsTemplate;
        leads: Lead;
        blog_posts: BlogPost;
        faqs: Faq;
        media: Media;
        'audit-logs': AuditLog;
        'payload-kv': PayloadKv;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        tenants: TenantsSelect<false> | TenantsSelect<true>;
        users: UsersSelect<false> | UsersSelect<true>;
        cycles: CyclesSelect<false> | CyclesSelect<true>;
        campuses: CampusesSelect<false> | CampusesSelect<true>;
        'areas-formativas': AreasFormativasSelect<false> | AreasFormativasSelect<true>;
        'entidades-financiadoras': EntidadesFinanciadorasSelect<false> | EntidadesFinanciadorasSelect<true>;
        courses: CoursesSelect<false> | CoursesSelect<true>;
        'course-runs': CourseRunsSelect<false> | CourseRunsSelect<true>;
        students: StudentsSelect<false> | StudentsSelect<true>;
        enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
        staff: StaffSelect<false> | StaffSelect<true>;
        campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
        ads_templates: AdsTemplatesSelect<false> | AdsTemplatesSelect<true>;
        leads: LeadsSelect<false> | LeadsSelect<true>;
        blog_posts: BlogPostsSelect<false> | BlogPostsSelect<true>;
        faqs: FaqsSelect<false> | FaqsSelect<true>;
        media: MediaSelect<false> | MediaSelect<true>;
        'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
        'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    fallbackLocale: null;
    globals: {};
    globalsSelect: {};
    locale: null;
    user: User & {
        collection: 'users';
    };
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * Academias/Organizaciones del sistema multi-tenant
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
    id: number;
    /**
     * Nombre de la academia/organización (ej: "CEP Formación")
     */
    name: string;
    /**
     * Identificador único para URLs (ej: "cep-formacion")
     */
    slug: string;
    /**
     * Dominio personalizado (ej: "cep.example.com") - Opcional
     */
    domain?: string | null;
    branding?: {
        logo?: (number | null) | Media;
        favicon?: (number | null) | Media;
        /**
         * Color hexadecimal (ej: "#F2014B")
         */
        primaryColor?: string | null;
        secondaryColor?: string | null;
    };
    contact?: {
        email?: string | null;
        phone?: string | null;
        address?: string | null;
        website?: string | null;
    };
    settings?: {
        timezone?: ('Europe/Madrid' | 'Europe/London' | 'America/New_York' | 'America/Los_Angeles' | 'Atlantic/Canary') | null;
        language?: ('es' | 'en' | 'pt') | null;
        features?: {
            enableLeads?: boolean | null;
            enableCampaigns?: boolean | null;
            enableBlog?: boolean | null;
            enableAnalytics?: boolean | null;
        };
    };
    /**
     * Configuración de servicios externos
     */
    integrations?: {
        /**
         * Ej: G-XXXXXXXXXX
         */
        ga4MeasurementId?: string | null;
        metaPixelId?: string | null;
        /**
         * Para integración de email marketing
         */
        mailchimpApiKey?: string | null;
        whatsappBusinessId?: string | null;
    };
    /**
     * Desactivar para suspender acceso al tenant
     */
    active?: boolean | null;
    limits?: {
        maxUsers?: number | null;
        maxCourses?: number | null;
        maxLeadsPerMonth?: number | null;
        storageQuotaMB?: number | null;
    };
    /**
     * Notas visibles solo para SuperAdmin
     */
    notes?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: number;
    alt: string;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        thumbnail?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        card?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        hero?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * System users with authentication and role-based access control
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    password: string | null;
    /**
     * Full name of the user
     */
    name: string;
    /**
     * User access level and permissions
     */
    role: 'superadmin' | 'admin' | 'gestor' | 'marketing' | 'asesor' | 'lectura';
    /**
     * Academia/Organización asignada
     */
    tenant?: (number | null) | Tenant;
    /**
     * URL to profile picture
     */
    avatar_url?: string | null;
    /**
     * Phone number (format: +34 XXX XXX XXX)
     */
    phone?: string | null;
    /**
     * Account active status
     */
    is_active?: boolean | null;
    /**
     * Last login timestamp
     */
    last_login_at?: string | null;
    /**
     * Total number of logins
     */
    login_count?: number | null;
    updatedAt: string;
    createdAt: string;
    /**
     * Email address (used for login)
     */
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?: {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
    }[] | null;
}
/**
 * Educational cycles that categorize courses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cycles".
 */
export interface Cycle {
    id: number;
    /**
     * URL-friendly identifier (auto-generated from name if not provided)
     */
    slug: string;
    /**
     * Display name of the cycle
     */
    name: string;
    /**
     * Detailed description of the cycle
     */
    description?: string | null;
    /**
     * Educational level of the cycle
     */
    level: 'fp_basica' | 'grado_medio' | 'grado_superior' | 'certificado_profesionalidad';
    /**
     * Display order (lower numbers appear first)
     */
    order_display?: number | null;
    /**
     * Academia/Organización propietaria
     */
    tenant?: (number | null) | Tenant;
    updatedAt: string;
    createdAt: string;
}
/**
 * Physical locations where courses are offered
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campuses".
 */
export interface Campus {
    id: number;
    /**
     * URL-friendly identifier (auto-generated from name if not provided)
     */
    slug: string;
    /**
     * Display name of the campus (e.g., "Madrid Centro")
     */
    name: string;
    /**
     * City where the campus is located (e.g., "Madrid")
     */
    city: string;
    /**
     * Full street address of the campus
     */
    address?: string | null;
    /**
     * Spanish postal code (5 digits, e.g., "28001")
     */
    postal_code?: string | null;
    /**
     * Spanish phone number format: +34 XXX XXX XXX
     */
    phone?: string | null;
    /**
     * Contact email for the campus
     */
    email?: string | null;
    /**
     * Google Maps URL for the campus location
     */
    maps_url?: string | null;
    /**
     * Staff members (professors and administrativos) assigned to this campus
     */
    staff_members?: (number | Staff)[] | null;
    /**
     * Academia/Organización propietaria
     */
    tenant?: (number | null) | Tenant;
    updatedAt: string;
    createdAt: string;
}
/**
 * Professors and administrative staff across all campuses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
    id: number;
    /**
     * Type of staff member (profesor or administrativo)
     */
    staff_type: 'profesor' | 'administrativo';
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Full name (auto-generated from first_name + last_name)
     */
    full_name?: string | null;
    /**
     * Email address (must be unique)
     */
    email: string;
    /**
     * Phone number (Spanish format: +34 XXX XXX XXX)
     */
    phone?: string | null;
    /**
     * Short biography or description
     */
    bio?: string | null;
    /**
     * Profile photo
     */
    photo?: (number | null) | Media;
    /**
     * Job position/title (e.g., "Profesor de Marketing Digital", "Coordinador Académico")
     */
    position: string;
    /**
     * Type of employment contract
     */
    contract_type: 'full_time' | 'part_time' | 'freelance';
    /**
     * Current employment status
     */
    employment_status: 'active' | 'temporary_leave' | 'inactive';
    /**
     * Date of hire / Start date
     */
    hire_date: string;
    /**
     * Specialties (for professors only)
     */
    specialties?: ('marketing-digital' | 'desarrollo-web' | 'diseno-grafico' | 'audiovisual' | 'gestion-empresarial' | 'redes-sociales' | 'seo-sem' | 'ecommerce' | 'fotografia' | 'video')[] | null;
    /**
     * Certifications and academic titles (for professors only)
     */
    certifications?: {
        /**
         * Certification or degree title
         */
        title: string;
        /**
         * Issuing institution
         */
        institution: string;
        /**
         * Year obtained
         */
        year: number;
        /**
         * Certificate PDF or image (optional)
         */
        document?: (number | null) | Media;
        id?: string | null;
    }[] | null;
    /**
     * Campuses where this staff member can work (select at least one)
     */
    assigned_campuses: (number | Campus)[];
    /**
     * Is this staff member currently active?
     */
    is_active?: boolean | null;
    /**
     * Internal notes (not visible to public)
     */
    notes?: string | null;
    /**
     * User who created this staff member (auto-populated)
     */
    created_by?: (number | null) | User;
    updatedAt: string;
    createdAt: string;
}
/**
 * Áreas de conocimiento para categorización de cursos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas-formativas".
 */
export interface AreasFormativa {
    id: number;
    /**
     * Nombre del área formativa (ej: Marketing Digital)
     */
    nombre: string;
    /**
     * Código único (3-4 letras mayúsculas, ej: MKT, DEV)
     */
    codigo: string;
    /**
     * Descripción del área formativa (opcional)
     */
    descripcion?: string | null;
    /**
     * Color en formato hexadecimal (ej: #FF5733)
     */
    color?: string | null;
    /**
     * Áreas activas aparecen en el selector de cursos
     */
    activo?: boolean | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * Entidades que financian cursos (subvenciones, becas)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entidades-financiadoras".
 */
export interface EntidadesFinanciadora {
    id: number;
    /**
     * Nombre completo de la entidad (ej: FUNDAE, SEPE)
     */
    nombre: string;
    /**
     * Código único identificador (ej: fundae, sepe, fse)
     */
    codigo: string;
    /**
     * Descripción de la entidad y sus programas
     */
    descripcion?: string | null;
    /**
     * URL del logo (subido a MinIO/S3)
     */
    logo_url?: string | null;
    /**
     * Tipo de subvención que ofrece
     */
    tipo_subvencion: 'publica' | 'privada' | 'europea' | 'autonomica';
    /**
     * URL del sitio web oficial
     */
    url_oficial?: string | null;
    /**
     * Entidades inactivas no aparecen en formularios
     */
    activo?: boolean | null;
    created_by?: (number | null) | User;
    updatedAt: string;
    createdAt: string;
}
/**
 * Educational course catalog with pricing, modality, and campus information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
    id: number;
    /**
     * Código único auto-generado (ej: MKT-PRIV-0001)
     */
    codigo: string;
    /**
     * Auto-generated from name. Lowercase, hyphens only.
     */
    slug: string;
    /**
     * Course name (max 500 characters)
     */
    name: string;
    /**
     * Main image displayed on course cards and detail page
     */
    featured_image?: (number | null) | Media;
    /**
     * The educational cycle this course belongs to (optional)
     */
    cycle?: (number | null) | Cycle;
    /**
     * Campuses where this course is offered (leave empty for online-only courses)
     */
    campuses?: (number | Campus)[] | null;
    /**
     * Brief course summary for listings (optional)
     */
    short_description?: string | null;
    /**
     * Detailed course information (optional)
     */
    long_description?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    /**
     * Course delivery method
     */
    modality: 'presencial' | 'online' | 'hibrido';
    /**
     * Type of course offering (determines pricing and visibility)
     */
    course_type?: ('privado' | 'ocupados' | 'desempleados' | 'teleformacion' | 'ciclo_medio' | 'ciclo_superior') | null;
    /**
     * Área de conocimiento del curso
     */
    area_formativa: number | AreasFormativa;
    /**
     * Thematic area for filtering courses (e.g., technology, healthcare, marketing)
     */
    area?: ('sanitaria' | 'horeca' | 'salud' | 'tecnologia' | 'audiovisual' | 'administracion' | 'marketing' | 'educacion') | null;
    /**
     * Course duration in hours (must be positive)
     */
    duration_hours?: number | null;
    /**
     * Base price in euros (2 decimal places)
     */
    base_price?: number | null;
    /**
     * Subsidy percentage (0-100%). Use 100 for fully subsidized courses.
     */
    subsidy_percentage?: number | null;
    /**
     * Whether financial aid is available for this course
     */
    financial_aid_available?: boolean | null;
    /**
     * Active courses are visible to the public
     */
    active?: boolean | null;
    /**
     * Featured courses appear prominently on the homepage
     */
    featured?: boolean | null;
    /**
     * SEO meta title (optional, max 300 chars)
     */
    meta_title?: string | null;
    /**
     * SEO meta description (optional, max 500 chars)
     */
    meta_description?: string | null;
    /**
     * User who created this course
     */
    created_by?: (number | null) | User;
    /**
     * Academia/Organización propietaria
     */
    tenant?: (number | null) | Tenant;
    updatedAt: string;
    createdAt: string;
}
/**
 * Specific course offerings with scheduling, capacity, and enrollment tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-runs".
 */
export interface CourseRun {
    id: number;
    /**
     * The course being offered in this run
     */
    course: number | Course;
    /**
     * Campus where this course run takes place (optional for online courses)
     */
    campus?: (number | null) | Campus;
    /**
     * Código único auto-generado (ej: NOR-2025-001)
     */
    codigo: string;
    /**
     * Date when the course run starts
     */
    start_date: string;
    /**
     * Date when the course run ends (must be after start_date)
     */
    end_date: string;
    /**
     * Last date to enroll (must be before start_date)
     */
    enrollment_deadline?: string | null;
    /**
     * Days of the week when classes occur
     */
    schedule_days?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[] | null;
    /**
     * Class start time (HH:MM:SS format, e.g., 09:00:00)
     */
    schedule_time_start?: string | null;
    /**
     * Class end time (HH:MM:SS format, e.g., 13:00:00)
     */
    schedule_time_end?: string | null;
    /**
     * Maximum number of students allowed (must be greater than min_students)
     */
    max_students: number;
    /**
     * Minimum number of students required to run the course
     */
    min_students: number;
    /**
     * Current number of enrolled students (auto-managed by enrollment system)
     */
    current_enrollments: number;
    /**
     * Current status of the course run
     */
    status: 'draft' | 'published' | 'enrollment_open' | 'enrollment_closed' | 'in_progress' | 'completed' | 'cancelled';
    /**
     * Override course default price (leave empty to use course price)
     */
    price_override?: number | null;
    /**
     * Is financial aid available for this course run?
     */
    financial_aid_available?: boolean | null;
    /**
     * Professor assigned to teach this course run
     */
    instructor?: (number | null) | Staff;
    /**
     * Internal notes about this course run (not visible to public)
     */
    notes?: string | null;
    /**
     * Historical data captured when the course run was completed
     */
    completion_snapshot?: {
        /**
         * Number of students who completed the course
         */
        final_student_count?: number | null;
        /**
         * Actual occupation percentage (final_student_count / max_students * 100)
         */
        final_occupation_percentage?: number | null;
        /**
         * Final price per student (for historical reference)
         */
        final_price?: number | null;
        /**
         * Date when the course run was marked as completed
         */
        completed_at?: string | null;
    };
    /**
     * User who created this course run (auto-populated)
     */
    created_by?: (number | null) | User;
    /**
     * Academia/Organización propietaria
     */
    tenant?: (number | null) | Tenant;
    updatedAt: string;
    createdAt: string;
}
/**
 * Student/learner profiles with complete PII and GDPR compliance
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
    id: number;
    /**
     * Student first name (PII)
     */
    first_name: string;
    /**
     * Student last name (PII)
     */
    last_name: string;
    /**
     * Student email address (PII - unique, GDPR protected)
     */
    email: string;
    /**
     * Phone number in Spanish format: +34 XXX XXX XXX (PII)
     */
    phone: string;
    /**
     * Spanish DNI/NIE (8 digits + letter) - HIGHLY SENSITIVE PII
     */
    dni?: string | null;
    /**
     * Street address (PII)
     */
    address?: string | null;
    /**
     * City (PII)
     */
    city?: string | null;
    /**
     * Postal/ZIP code (PII)
     */
    postal_code?: string | null;
    /**
     * Country (default: España)
     */
    country?: string | null;
    /**
     * Date of birth (must be >= 16 years old) - PII
     */
    date_of_birth?: string | null;
    /**
     * Gender (optional)
     */
    gender?: ('male' | 'female' | 'non-binary' | 'prefer-not-to-say') | null;
    /**
     * Emergency contact full name (HIGHLY SENSITIVE PII)
     */
    emergency_contact_name?: string | null;
    /**
     * Emergency contact phone: +34 XXX XXX XXX (HIGHLY SENSITIVE PII)
     */
    emergency_contact_phone?: string | null;
    /**
     * Relationship to student (parent, spouse, etc.)
     */
    emergency_contact_relationship?: ('parent' | 'father' | 'mother' | 'guardian' | 'spouse' | 'partner' | 'sibling' | 'friend' | 'other') | null;
    /**
     * REQUIRED: GDPR consent (immutable after creation)
     */
    gdpr_consent: boolean;
    /**
     * REQUIRED: Privacy policy acceptance (immutable)
     */
    privacy_policy_accepted: boolean;
    /**
     * OPTIONAL: Consent to receive marketing communications
     */
    marketing_consent?: boolean | null;
    /**
     * Auto-captured: When consent was given (ISO 8601) - IMMUTABLE
     */
    consent_timestamp?: string | null;
    /**
     * Auto-captured: IP address when consent was given (PII) - IMMUTABLE
     */
    consent_ip_address?: string | null;
    /**
     * Current student status
     */
    status: 'active' | 'inactive' | 'suspended' | 'graduated';
    /**
     * Internal notes about this student (not visible to student)
     */
    notes?: string | null;
    /**
     * User who created this student (auto-populated, immutable)
     */
    created_by?: (number | null) | User;
    updatedAt: string;
    createdAt: string;
}
/**
 * Student enrollments in course runs with payment and academic tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
    id: number;
    /**
     * The student enrolling in the course run
     */
    student: number | Lead;
    /**
     * The specific course run the student is enrolling in
     */
    course_run: number | CourseRun;
    /**
     * Current enrollment status
     */
    status: 'pending' | 'confirmed' | 'waitlisted' | 'cancelled' | 'completed' | 'withdrawn';
    /**
     * Payment status (auto-calculated based on amounts)
     */
    payment_status: 'pending' | 'partial' | 'paid' | 'refunded' | 'waived';
    /**
     * Total amount due for this enrollment
     */
    total_amount: number;
    /**
     * Amount already paid by student
     */
    amount_paid: number;
    /**
     * Has the student applied for financial aid?
     */
    financial_aid_applied?: boolean | null;
    /**
     * Amount of financial aid approved/requested
     */
    financial_aid_amount?: number | null;
    /**
     * Status of financial aid application
     */
    financial_aid_status?: ('none' | 'pending' | 'approved' | 'rejected') | null;
    /**
     * When the student enrolled (auto-populated)
     */
    enrolled_at?: string | null;
    /**
     * When enrollment was confirmed (auto-populated)
     */
    confirmed_at?: string | null;
    /**
     * When student completed the course (auto-populated)
     */
    completed_at?: string | null;
    /**
     * When enrollment was cancelled or withdrawn (auto-populated)
     */
    cancelled_at?: string | null;
    /**
     * Student attendance percentage (0-100)
     */
    attendance_percentage?: number | null;
    /**
     * Student final grade (0-100)
     */
    final_grade?: number | null;
    /**
     * Has a certificate been issued to the student?
     */
    certificate_issued?: boolean | null;
    /**
     * URL to the issued certificate (immutable once set)
     */
    certificate_url?: string | null;
    /**
     * Internal notes about this enrollment (not visible to students)
     */
    notes?: string | null;
    /**
     * Reason for cancellation or withdrawal
     */
    cancellation_reason?: string | null;
    /**
     * User who created this enrollment (auto-populated)
     */
    created_by?: (number | null) | User;
    updatedAt: string;
    createdAt: string;
}
/**
 * Lead submissions with GDPR compliance and automated scoring
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
    id: number;
    /**
     * First name of the lead (PII)
     */
    first_name: string;
    /**
     * Last name of the lead (PII)
     */
    last_name: string;
    /**
     * Email address (PII - protected by GDPR)
     */
    email: string;
    /**
     * Phone number in Spanish format: +34 XXX XXX XXX (PII)
     */
    phone: string;
    /**
     * Course the lead is interested in (optional)
     */
    course?: (number | null) | Course;
    /**
     * Preferred campus location (optional)
     */
    campus?: (number | null) | Campus;
    /**
     * Marketing campaign source (optional)
     */
    campaign?: (number | null) | Campaign;
    /**
     * Additional message or questions from the lead (PII)
     */
    message?: string | null;
    /**
     * How the lead prefers to be contacted
     */
    preferred_contact_method?: ('email' | 'phone' | 'whatsapp') | null;
    /**
     * Best time to contact the lead
     */
    preferred_contact_time?: ('morning' | 'afternoon' | 'evening' | 'anytime') | null;
    /**
     * REQUIRED: GDPR consent to process personal data
     */
    gdpr_consent: boolean;
    /**
     * REQUIRED: Privacy policy acceptance
     */
    privacy_policy_accepted: boolean;
    /**
     * OPTIONAL: Consent to receive marketing communications
     */
    marketing_consent?: boolean | null;
    /**
     * Auto-captured: When consent was given (ISO 8601)
     */
    consent_timestamp?: string | null;
    /**
     * Auto-captured: IP address when consent was given
     */
    consent_ip_address?: string | null;
    /**
     * Current status of the lead
     */
    status: 'new' | 'contacted' | 'qualified' | 'converted' | 'rejected' | 'spam';
    /**
     * User assigned to follow up with this lead
     */
    assigned_to?: (number | null) | User;
    /**
     * Lead priority level
     */
    priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
    /**
     * Marketing attribution parameters
     */
    utm?: {
        /**
         * UTM source (e.g., google, facebook)
         */
        source?: string | null;
        /**
         * UTM medium (e.g., cpc, email)
         */
        medium?: string | null;
        /**
         * UTM campaign (e.g., summer-2025)
         */
        campaign?: string | null;
        /**
         * UTM term (keywords)
         */
        term?: string | null;
        /**
         * UTM content (ad variant)
         */
        content?: string | null;
    };
    /**
     * MailChimp subscriber ID (auto-populated)
     */
    mailchimp_subscriber_id?: string | null;
    /**
     * WhatsApp contact ID (auto-populated)
     */
    whatsapp_contact_id?: string | null;
    /**
     * Calculated lead score (0-100) - auto-computed
     */
    lead_score?: number | null;
    /**
     * Internal notes about this lead (not visible to lead)
     */
    notes?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    /**
     * When was this lead last contacted
     */
    last_contacted_at?: string | null;
    /**
     * When the lead was converted (auto-set when status = converted)
     */
    converted_at?: string | null;
    /**
     * Academia/Organización propietaria
     */
    tenant?: (number | null) | Tenant;
    updatedAt: string;
    createdAt: string;
}
/**
 * Marketing campaigns with UTM tracking, budget management, and ROI analytics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
    id: number;
    /**
     * Unique campaign name (e.g., "Spring Enrollment 2025")
     */
    name: string;
    /**
     * Campaign description and objectives (optional)
     */
    description?: string | null;
    /**
     * Type of marketing campaign
     */
    campaign_type: 'email' | 'social' | 'paid_ads' | 'organic' | 'event' | 'referral' | 'other';
    /**
     * Campaign status (draft → active → paused/completed → archived)
     */
    status: 'draft' | 'active' | 'paused' | 'completed' | 'archived';
    /**
     * Optional: Specific course this campaign promotes
     */
    course?: (number | null) | Course;
    /**
     * UTM Source: Traffic source (e.g., google, facebook, newsletter)
     */
    utm_source?: string | null;
    /**
     * UTM Medium: Marketing medium (e.g., cpc, email, social)
     */
    utm_medium?: string | null;
    /**
     * UTM Campaign: Campaign identifier (REQUIRED if any other UTM provided)
     */
    utm_campaign?: string | null;
    /**
     * UTM Term: Paid keywords (optional)
     */
    utm_term?: string | null;
    /**
     * UTM Content: Content variant for A/B testing (optional)
     */
    utm_content?: string | null;
    /**
     * Campaign start date (REQUIRED)
     */
    start_date: string;
    /**
     * Campaign end date (optional - leave blank for ongoing campaigns)
     */
    end_date?: string | null;
    /**
     * Campaign budget (optional, in EUR)
     */
    budget?: number | null;
    /**
     * Target number of leads (optional)
     */
    target_leads?: number | null;
    /**
     * Target number of enrollments (optional, must be <= target_leads)
     */
    target_enrollments?: number | null;
    /**
     * Auto-calculated: Total leads from this campaign (IMMUTABLE)
     */
    total_leads?: number | null;
    /**
     * Auto-calculated: Leads that enrolled (IMMUTABLE)
     */
    total_conversions?: number | null;
    /**
     * Auto-calculated: (conversions / leads) * 100 (IMMUTABLE)
     */
    conversion_rate?: number | null;
    /**
     * Auto-calculated: budget / total_leads (IMMUTABLE)
     */
    cost_per_lead?: number | null;
    /**
     * Internal notes about this campaign (not visible to public)
     */
    notes?: string | null;
    /**
     * User who created this campaign (auto-populated, IMMUTABLE)
     */
    created_by?: (number | null) | User;
    /**
     * Academia/Organización propietaria
     */
    tenant?: (number | null) | Tenant;
    updatedAt: string;
    createdAt: string;
}
/**
 * Reusable ad templates for marketing campaigns (email, social, display ads)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_templates".
 */
export interface AdsTemplate {
    id: number;
    /**
     * Unique template name (e.g., "Spring Email Template 2025")
     */
    name: string;
    /**
     * Template description and usage notes (optional)
     */
    description?: string | null;
    /**
     * Type of marketing template
     */
    template_type: 'email' | 'social_post' | 'display_ad' | 'landing_page' | 'video_script' | 'other';
    /**
     * Template status (draft → active → archived)
     */
    status: 'draft' | 'active' | 'archived';
    /**
     * Optional: Specific campaign this template is for
     */
    campaign?: (number | null) | Campaign;
    /**
     * Ad headline or email subject line (max 100 characters)
     */
    headline: string;
    /**
     * Main ad copy or email body (rich text)
     */
    body_copy: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    /**
     * Call-to-action text (e.g., "Enroll Now") - max 50 characters
     */
    call_to_action?: string | null;
    /**
     * Call-to-action destination URL (optional)
     */
    cta_url?: string | null;
    /**
     * Main image/creative URL (optional)
     */
    primary_image_url?: string | null;
    /**
     * Secondary image URL (optional)
     */
    secondary_image_url?: string | null;
    /**
     * Video asset URL (optional)
     */
    video_url?: string | null;
    /**
     * Thumbnail preview URL (optional)
     */
    thumbnail_url?: string | null;
    /**
     * Target demographic/audience description (optional)
     */
    target_audience?: string | null;
    /**
     * Ad tone and style
     */
    tone: 'professional' | 'casual' | 'urgent' | 'friendly' | 'educational' | 'promotional';
    /**
     * Content language
     */
    language: 'es' | 'en' | 'ca';
    /**
     * Template tags for filtering/search (max 10, lowercase, alphanumeric + hyphens)
     */
    tags?: string[] | null;
    /**
     * Template version number (immutable, starts at 1)
     */
    version?: number | null;
    /**
     * How many times this template has been used (system-tracked, IMMUTABLE)
     */
    usage_count?: number | null;
    /**
     * Last usage timestamp (system-tracked, IMMUTABLE)
     */
    last_used_at?: string | null;
    /**
     * Active status (false = soft deleted)
     */
    active?: boolean | null;
    /**
     * When template was archived (auto-set, IMMUTABLE)
     */
    archived_at?: string | null;
    /**
     * User who created this template (auto-populated, IMMUTABLE)
     */
    created_by?: (number | null) | User;
    updatedAt: string;
    createdAt: string;
}
/**
 * Blog posts with SEO optimization and publication workflow
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_posts".
 */
export interface BlogPost {
    id: number;
    /**
     * Blog post title (10-120 characters)
     */
    title: string;
    /**
     * URL-safe slug (auto-generated from title with Spanish normalization)
     */
    slug: string;
    /**
     * Blog post excerpt for previews (50-300 characters)
     */
    excerpt: string;
    /**
     * Main blog post content (rich text)
     */
    content: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    /**
     * Featured image URL (optional)
     */
    featured_image?: string | null;
    /**
     * Open Graph image for social sharing (optional)
     */
    og_image?: string | null;
    /**
     * Publication status (draft → published → archived)
     */
    status: 'draft' | 'published' | 'archived';
    /**
     * Featured on homepage
     */
    featured?: boolean | null;
    /**
     * Publication timestamp (auto-set, IMMUTABLE)
     */
    published_at?: string | null;
    /**
     * Archive timestamp (auto-set, IMMUTABLE)
     */
    archived_at?: string | null;
    /**
     * Post author (auto-populated, IMMUTABLE)
     */
    author: number | User;
    /**
     * User who created this post (auto-populated, IMMUTABLE)
     */
    created_by?: (number | null) | User;
    /**
     * Post tags (max 10, lowercase, alphanumeric + hyphens)
     */
    tags?: string[] | null;
    /**
     * Related courses (max 5)
     */
    related_courses?: (number | Course)[] | null;
    /**
     * View count (system-tracked, IMMUTABLE)
     */
    view_count?: number | null;
    /**
     * Estimated read time in minutes (auto-calculated, IMMUTABLE)
     */
    estimated_read_time?: number | null;
    /**
     * SEO meta title (50-70 characters for optimal search display)
     */
    meta_title?: string | null;
    /**
     * SEO meta description (120-160 characters for optimal search display)
     */
    meta_description?: string | null;
    /**
     * Content language
     */
    language: 'es' | 'en' | 'ca';
    updatedAt: string;
    createdAt: string;
}
/**
 * Frequently Asked Questions with category organization and multi-language support
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
    id: number;
    /**
     * FAQ question (10-200 characters)
     */
    question: string;
    /**
     * URL-safe slug (auto-generated from question with Spanish normalization)
     */
    slug: string;
    /**
     * FAQ answer (rich text)
     */
    answer: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    /**
     * FAQ category (courses, enrollment, payments, technical, general)
     */
    category: 'courses' | 'enrollment' | 'payments' | 'technical' | 'general';
    /**
     * Publication status (draft → published → archived)
     */
    status: 'draft' | 'published' | 'archived';
    /**
     * Featured on homepage
     */
    featured?: boolean | null;
    /**
     * Publication timestamp (auto-set, IMMUTABLE)
     */
    published_at?: string | null;
    /**
     * Archive timestamp (auto-set, IMMUTABLE)
     */
    archived_at?: string | null;
    /**
     * User who created this FAQ (auto-populated, IMMUTABLE)
     */
    created_by?: (number | null) | User;
    /**
     * Search keywords (max 10, each max 50 chars)
     */
    keywords?: string[] | null;
    /**
     * Display order (0 = first, higher numbers appear later)
     */
    order?: number | null;
    /**
     * Related course (optional)
     */
    related_course?: (number | null) | Course;
    /**
     * View count (system-tracked, IMMUTABLE)
     */
    view_count?: number | null;
    /**
     * Helpful count (user feedback, system-managed, IMMUTABLE)
     */
    helpful_count?: number | null;
    /**
     * Content language
     */
    language: 'es' | 'en' | 'ca';
    updatedAt: string;
    createdAt: string;
}
/**
 * Immutable audit trail for GDPR Article 30 compliance. Logs all system operations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
    id: number;
    /**
     * CRUD operation or security event
     */
    action: 'create' | 'read' | 'update' | 'delete' | 'export' | 'login' | 'logout' | 'permission_change';
    /**
     * Target Payload collection slug
     */
    collection_name: 'users' | 'cycles' | 'campuses' | 'courses' | 'course-runs' | 'leads' | 'enrollments' | 'students' | 'campaigns' | 'ads-templates' | 'blog-posts' | 'faqs' | 'media' | 'audit-logs';
    /**
     * ID of affected document (null for bulk operations)
     */
    document_id?: string | null;
    /**
     * User who performed the action
     */
    user_id: number | User;
    /**
     * Snapshot of user email (preserved if user is deleted) - IMMUTABLE
     */
    user_email: string;
    /**
     * User role at time of action (snapshot) - IMMUTABLE
     */
    user_role: 'admin' | 'gestor' | 'marketing' | 'asesor' | 'lectura';
    /**
     * Client IP address (IPv4 or IPv6) - PII, IMMUTABLE, Admin/Gestor only
     */
    ip_address: string;
    /**
     * Browser/client information - IMMUTABLE
     */
    user_agent?: string | null;
    /**
     * Before/after snapshots for updates (sanitized, no passwords) - IMMUTABLE
     */
    changes?: {
        [k: string]: unknown;
    } | unknown[] | string | number | boolean | null;
    /**
     * Additional context (headers, query params, custom data) - IMMUTABLE
     */
    metadata?: {
        [k: string]: unknown;
    } | unknown[] | string | number | boolean | null;
    /**
     * Operation outcome (success/failure/blocked)
     */
    status: 'success' | 'failure' | 'blocked';
    /**
     * Error details if status = failure (no PII) - IMMUTABLE
     */
    error_message?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: number;
    key: string;
    data: {
        [k: string]: unknown;
    } | unknown[] | string | number | boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?: ({
        relationTo: 'tenants';
        value: number | Tenant;
    } | null) | ({
        relationTo: 'users';
        value: number | User;
    } | null) | ({
        relationTo: 'cycles';
        value: number | Cycle;
    } | null) | ({
        relationTo: 'campuses';
        value: number | Campus;
    } | null) | ({
        relationTo: 'areas-formativas';
        value: number | AreasFormativa;
    } | null) | ({
        relationTo: 'entidades-financiadoras';
        value: number | EntidadesFinanciadora;
    } | null) | ({
        relationTo: 'courses';
        value: number | Course;
    } | null) | ({
        relationTo: 'course-runs';
        value: number | CourseRun;
    } | null) | ({
        relationTo: 'students';
        value: number | Student;
    } | null) | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
    } | null) | ({
        relationTo: 'staff';
        value: number | Staff;
    } | null) | ({
        relationTo: 'campaigns';
        value: number | Campaign;
    } | null) | ({
        relationTo: 'ads_templates';
        value: number | AdsTemplate;
    } | null) | ({
        relationTo: 'leads';
        value: number | Lead;
    } | null) | ({
        relationTo: 'blog_posts';
        value: number | BlogPost;
    } | null) | ({
        relationTo: 'faqs';
        value: number | Faq;
    } | null) | ({
        relationTo: 'media';
        value: number | Media;
    } | null) | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
    } | null);
    globalSlug?: string | null;
    user: {
        relationTo: 'users';
        value: number | User;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user: {
        relationTo: 'users';
        value: number | User;
    };
    key?: string | null;
    value?: {
        [k: string]: unknown;
    } | unknown[] | string | number | boolean | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
    name?: T;
    slug?: T;
    domain?: T;
    branding?: T | {
        logo?: T;
        favicon?: T;
        primaryColor?: T;
        secondaryColor?: T;
    };
    contact?: T | {
        email?: T;
        phone?: T;
        address?: T;
        website?: T;
    };
    settings?: T | {
        timezone?: T;
        language?: T;
        features?: T | {
            enableLeads?: T;
            enableCampaigns?: T;
            enableBlog?: T;
            enableAnalytics?: T;
        };
    };
    integrations?: T | {
        ga4MeasurementId?: T;
        metaPixelId?: T;
        mailchimpApiKey?: T;
        whatsappBusinessId?: T;
    };
    active?: T;
    limits?: T | {
        maxUsers?: T;
        maxCourses?: T;
        maxLeadsPerMonth?: T;
        storageQuotaMB?: T;
    };
    notes?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    password?: T;
    name?: T;
    role?: T;
    tenant?: T;
    avatar_url?: T;
    phone?: T;
    is_active?: T;
    last_login_at?: T;
    login_count?: T;
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?: T | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cycles_select".
 */
export interface CyclesSelect<T extends boolean = true> {
    slug?: T;
    name?: T;
    description?: T;
    level?: T;
    order_display?: T;
    tenant?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campuses_select".
 */
export interface CampusesSelect<T extends boolean = true> {
    slug?: T;
    name?: T;
    city?: T;
    address?: T;
    postal_code?: T;
    phone?: T;
    email?: T;
    maps_url?: T;
    staff_members?: T;
    tenant?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas-formativas_select".
 */
export interface AreasFormativasSelect<T extends boolean = true> {
    nombre?: T;
    codigo?: T;
    descripcion?: T;
    color?: T;
    activo?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entidades-financiadoras_select".
 */
export interface EntidadesFinanciadorasSelect<T extends boolean = true> {
    nombre?: T;
    codigo?: T;
    descripcion?: T;
    logo_url?: T;
    tipo_subvencion?: T;
    url_oficial?: T;
    activo?: T;
    created_by?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
    codigo?: T;
    slug?: T;
    name?: T;
    featured_image?: T;
    cycle?: T;
    campuses?: T;
    short_description?: T;
    long_description?: T;
    modality?: T;
    course_type?: T;
    area_formativa?: T;
    area?: T;
    duration_hours?: T;
    base_price?: T;
    subsidy_percentage?: T;
    financial_aid_available?: T;
    active?: T;
    featured?: T;
    meta_title?: T;
    meta_description?: T;
    created_by?: T;
    tenant?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-runs_select".
 */
export interface CourseRunsSelect<T extends boolean = true> {
    course?: T;
    campus?: T;
    codigo?: T;
    start_date?: T;
    end_date?: T;
    enrollment_deadline?: T;
    schedule_days?: T;
    schedule_time_start?: T;
    schedule_time_end?: T;
    max_students?: T;
    min_students?: T;
    current_enrollments?: T;
    status?: T;
    price_override?: T;
    financial_aid_available?: T;
    instructor?: T;
    notes?: T;
    completion_snapshot?: T | {
        final_student_count?: T;
        final_occupation_percentage?: T;
        final_price?: T;
        completed_at?: T;
    };
    created_by?: T;
    tenant?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
    first_name?: T;
    last_name?: T;
    email?: T;
    phone?: T;
    dni?: T;
    address?: T;
    city?: T;
    postal_code?: T;
    country?: T;
    date_of_birth?: T;
    gender?: T;
    emergency_contact_name?: T;
    emergency_contact_phone?: T;
    emergency_contact_relationship?: T;
    gdpr_consent?: T;
    privacy_policy_accepted?: T;
    marketing_consent?: T;
    consent_timestamp?: T;
    consent_ip_address?: T;
    status?: T;
    notes?: T;
    created_by?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
    student?: T;
    course_run?: T;
    status?: T;
    payment_status?: T;
    total_amount?: T;
    amount_paid?: T;
    financial_aid_applied?: T;
    financial_aid_amount?: T;
    financial_aid_status?: T;
    enrolled_at?: T;
    confirmed_at?: T;
    completed_at?: T;
    cancelled_at?: T;
    attendance_percentage?: T;
    final_grade?: T;
    certificate_issued?: T;
    certificate_url?: T;
    notes?: T;
    cancellation_reason?: T;
    created_by?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
    staff_type?: T;
    first_name?: T;
    last_name?: T;
    full_name?: T;
    email?: T;
    phone?: T;
    bio?: T;
    photo?: T;
    position?: T;
    contract_type?: T;
    employment_status?: T;
    hire_date?: T;
    specialties?: T;
    certifications?: T | {
        title?: T;
        institution?: T;
        year?: T;
        document?: T;
        id?: T;
    };
    assigned_campuses?: T;
    is_active?: T;
    notes?: T;
    created_by?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
    name?: T;
    description?: T;
    campaign_type?: T;
    status?: T;
    course?: T;
    utm_source?: T;
    utm_medium?: T;
    utm_campaign?: T;
    utm_term?: T;
    utm_content?: T;
    start_date?: T;
    end_date?: T;
    budget?: T;
    target_leads?: T;
    target_enrollments?: T;
    total_leads?: T;
    total_conversions?: T;
    conversion_rate?: T;
    cost_per_lead?: T;
    notes?: T;
    created_by?: T;
    tenant?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_templates_select".
 */
export interface AdsTemplatesSelect<T extends boolean = true> {
    name?: T;
    description?: T;
    template_type?: T;
    status?: T;
    campaign?: T;
    headline?: T;
    body_copy?: T;
    call_to_action?: T;
    cta_url?: T;
    primary_image_url?: T;
    secondary_image_url?: T;
    video_url?: T;
    thumbnail_url?: T;
    target_audience?: T;
    tone?: T;
    language?: T;
    tags?: T;
    version?: T;
    usage_count?: T;
    last_used_at?: T;
    active?: T;
    archived_at?: T;
    created_by?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
    first_name?: T;
    last_name?: T;
    email?: T;
    phone?: T;
    course?: T;
    campus?: T;
    campaign?: T;
    message?: T;
    preferred_contact_method?: T;
    preferred_contact_time?: T;
    gdpr_consent?: T;
    privacy_policy_accepted?: T;
    marketing_consent?: T;
    consent_timestamp?: T;
    consent_ip_address?: T;
    status?: T;
    assigned_to?: T;
    priority?: T;
    utm?: T | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
    };
    mailchimp_subscriber_id?: T;
    whatsapp_contact_id?: T;
    lead_score?: T;
    notes?: T;
    last_contacted_at?: T;
    converted_at?: T;
    tenant?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
    title?: T;
    slug?: T;
    excerpt?: T;
    content?: T;
    featured_image?: T;
    og_image?: T;
    status?: T;
    featured?: T;
    published_at?: T;
    archived_at?: T;
    author?: T;
    created_by?: T;
    tags?: T;
    related_courses?: T;
    view_count?: T;
    estimated_read_time?: T;
    meta_title?: T;
    meta_description?: T;
    language?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
    question?: T;
    slug?: T;
    answer?: T;
    category?: T;
    status?: T;
    featured?: T;
    published_at?: T;
    archived_at?: T;
    created_by?: T;
    keywords?: T;
    order?: T;
    related_course?: T;
    view_count?: T;
    helpful_count?: T;
    language?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?: T | {
        thumbnail?: T | {
            url?: T;
            width?: T;
            height?: T;
            mimeType?: T;
            filesize?: T;
            filename?: T;
        };
        card?: T | {
            url?: T;
            width?: T;
            height?: T;
            mimeType?: T;
            filesize?: T;
            filename?: T;
        };
        hero?: T | {
            url?: T;
            width?: T;
            height?: T;
            mimeType?: T;
            filesize?: T;
            filename?: T;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
    action?: T;
    collection_name?: T;
    document_id?: T;
    user_id?: T;
    user_email?: T;
    user_role?: T;
    ip_address?: T;
    user_agent?: T;
    changes?: T;
    metadata?: T;
    status?: T;
    error_message?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T;
    data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}
declare module 'payload' {
    interface GeneratedTypes extends Config {
    }
}
//# sourceMappingURL=payload-types.d.ts.map